# Generated by Django 3.1.1 on 2020-11-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20201105_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dateCreated',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='dateCompleted',
            new_name='datecompleted',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='userr',
            new_name='user',
        ),
    ]
